# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-11-19 11:11
from __future__ import unicode_literals

import dictatorMU.models
from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictatormu_group', to='otree.Session')),
            ],
            options={
                'db_table': 'dictatorMU_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('myrole', otree.db.models.StringField(max_length=10000, null=True)),
                ('profit1', otree.db.models.FloatField(null=True)),
                ('profit2', otree.db.models.FloatField(null=True)),
                ('profit3', otree.db.models.FloatField(null=True)),
                ('profit4', otree.db.models.FloatField(null=True)),
                ('ns6_1', dictatorMU.models.MyOwnField(null=True, verbose_name='I believe a <span class="alert alert-danger">sender</span> should give the following share of the\n        100 points to the receiver:')),
                ('ns6_2', dictatorMU.models.MyOwnField(null=True, verbose_name='I believe the <span class="alert alert-danger">receiver</span>  expects\n         from me as a sender to give him or her the following\n         share of the 100 points:')),
                ('ns6_3', dictatorMU.models.MyOwnField(null=True, verbose_name='I believe most <span class="alert alert-danger">senders</span> give the following share of the\n         100 points to receivers:')),
                ('ns6_4', dictatorMU.models.MyOwnField(null=True, verbose_name='I give the following amount of the 100 points\n        to the receiver:')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictatorMU.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictatormu_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictatormu_player', to='otree.Session')),
            ],
            options={
                'db_table': 'dictatorMU_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictatormu_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'dictatorMU_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictatorMU.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictatorMU.Subsession'),
        ),
    ]
