# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.currency
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('strategy', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('amount_offered', otree.db.models.CurrencyField(choices=[(otree.currency.Currency('0'), otree.currency.Currency('0')), (otree.currency.Currency('10'), otree.currency.Currency('10')), (otree.currency.Currency('20'), otree.currency.Currency('20')), (otree.currency.Currency('30'), otree.currency.Currency('30')), (otree.currency.Currency('40'), otree.currency.Currency('40')), (otree.currency.Currency('50'), otree.currency.Currency('50')), (otree.currency.Currency('60'), otree.currency.Currency('60')), (otree.currency.Currency('70'), otree.currency.Currency('70')), (otree.currency.Currency('80'), otree.currency.Currency('80')), (otree.currency.Currency('90'), otree.currency.Currency('90')), (otree.currency.Currency('100'), otree.currency.Currency('100'))], null=True)),
                ('offer_accepted', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_0', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 0 points?')),
                ('response_10', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 10 points?')),
                ('response_20', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 20 points?')),
                ('response_30', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 30 points?')),
                ('response_40', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 40 points?')),
                ('response_50', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 50 points?')),
                ('response_60', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 60 points?')),
                ('response_70', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 70 points?')),
                ('response_80', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 80 points?')),
                ('response_90', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 90 points?')),
                ('response_100', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you accept an offer of 100 points?')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimatum_group', to='otree.Session')),
            ],
            options={
                'db_table': 'ultimatum_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ultimatum.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimatum_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimatum_player', to='otree.Session')),
            ],
            options={
                'db_table': 'ultimatum_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimatum_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'ultimatum_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatum.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatum.Subsession'),
        ),
    ]
