# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='response_0',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_10',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_100',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_20',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_30',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_40',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_50',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_60',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_70',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_80',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_90',
        ),
    ]
