# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatum', '0002_auto_20180523_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='strategy',
        ),
    ]
