# Generated by Django 2.2.12 on 2020-11-19 21:54

import dg.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='norm_expectation',
            field=dg.models.MyOwnField(null=True, verbose_name='\n        Я полагаю, что  <span class="alert alert-danger">Пол</span>  expects\n         from me as a sender to give him or her the following\n         share of the 100 токен:'),
        ),
    ]
