# Generated by Django 2.2.12 on 2020-11-19 21:55

import dg.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0002_auto_20201120_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='norm_belief',
            field=dg.models.MyOwnField(null=True, verbose_name='Я считаю, что <span class="alert alert-danger">Отправитель</span> should give the following share of the\n        100 токен to the receiver:'),
        ),
    ]
