# Generated by Django 2.2.12 on 2020-11-19 21:57

import dg.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0005_auto_20201120_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='norm_expectation',
            field=dg.models.MyOwnField(null=True, verbose_name='\n        Я полагаю, что  <span class="alert alert-danger">Получатель</span>  expects\n         from me as a sender to give him or her the following\n         share of the 100 токен:'),
        ),
    ]
