# Generated by Django 2.2.12 on 2020-11-19 21:57

import dg.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0006_auto_20201120_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='norm_expectation',
            field=dg.models.MyOwnField(null=True, verbose_name='\n        Я полагаю, что в среднем <span class="alert alert-danger">Получатель</span>  ожидает \n         получить от Отправителя 100 токенов:'),
        ),
    ]
