# Generated by Django 2.2.12 on 2020-11-19 22:00

import dg.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0007_auto_20201120_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='decision',
            field=dg.models.MyOwnField(null=True, verbose_name='Я передаю отправителю из числа имеющихся у меня 100 токен токенов\n        :'),
        ),
        migrations.AlterField(
            model_name='player',
            name='empirical_expectation',
            field=dg.models.MyOwnField(null=True, verbose_name='Я думаю, что в среднем <span class="alert alert-danger">Получатель</span> передаст Отправителю\n         следующее число из 100 токен токенов:'),
        ),
        migrations.AlterField(
            model_name='player',
            name='norm_belief',
            field=dg.models.MyOwnField(null=True, verbose_name='Я считаю, что <span class="alert alert-danger">Отправитель</span> \n        должен отдать Получателю такую долю из \n        100 токенов:'),
        ),
        migrations.AlterField(
            model_name='player',
            name='norm_expectation',
            field=dg.models.MyOwnField(null=True, verbose_name='\n        Я полагаю, что в среднем <span class="alert alert-danger">Получатель</span>  ожидает \n         получить от Отправителя следующее число из 100 токенов:'),
        ),
    ]
