# Generated by Django 2.2.12 on 2020-11-19 22:00

import dg.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0008_auto_20201120_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='decision',
            field=dg.models.MyOwnField(null=True, verbose_name='Я передаю отправителю из числа имеющихся у меня 100 токенов\n        :'),
        ),
        migrations.AlterField(
            model_name='player',
            name='empirical_expectation',
            field=dg.models.MyOwnField(null=True, verbose_name='Я думаю, что в среднем <span class="alert alert-danger">Получатель</span> передаст Отправителю\n         следующее число из 100 токенов:'),
        ),
    ]
