# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-11-19 11:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('total_contribution', otree.db.models.IntegerField(null=True)),
                ('average_contribution', otree.db.models.FloatField(null=True)),
                ('individual_share', otree.db.models.CurrencyField(null=True)),
                ('punishmentmatrix', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=otree.db.models.IntegerField(null=True), null=True, size=4), null=True, size=4)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pggfg_group', to='otree.Session')),
            ],
            options={
                'db_table': 'pggfg_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('nickname', otree.db.models.StringField(help_text='(Any unique nickname works. It will help us to identify the winner)', max_length=100, null=True, verbose_name='Please enter your nickname')),
                ('cumulative_payoff', otree.db.models.FloatField(default=0, null=True)),
                ('punishment_sent', otree.db.models.IntegerField(null=True)),
                ('punishment_received', otree.db.models.IntegerField(null=True)),
                ('contribution', otree.db.models.PositiveIntegerField(null=True)),
                ('punishP1', otree.db.models.IntegerField(null=True, verbose_name='Participant 1')),
                ('punishP2', otree.db.models.IntegerField(null=True, verbose_name='Participant 2')),
                ('punishP3', otree.db.models.IntegerField(null=True, verbose_name='Participant 3')),
                ('punishP4', otree.db.models.IntegerField(null=True, verbose_name='Participant 4')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pggfg.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pggfg_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pggfg_player', to='otree.Session')),
            ],
            options={
                'db_table': 'pggfg_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('punishment', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pggfg_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'pggfg_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pggfg.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pggfg.Subsession'),
        ),
    ]
